name: BeaconWar
version: ${project.version}
main: com.beaconwar.BeaconWarPlugin
api-version: '1.20'
description: Team-based beacon control game
author: BeaconWar Team

commands:
  beaconwar:
    description: Main command for Beacon War
    aliases: [bw]
    usage: /<command> [setup|start|stop|join|status]
    permission: beaconwar.use
  nether:
    description: Teleport to the Nether
    usage: /<command>
    permission: beaconwar.admin
  overworld:
    description: Teleport to the Overworld
    usage: /<command>
    permission: beaconwar.admin
  setup:
    description: Set up beacons at your location
    usage: /<command>
    permission: beaconwar.admin
  start:
    description: Start the game
    usage: /<command> [minutes]
    permission: beaconwar.admin
  stop:
    description: Stop the game (no winner)
    usage: /<command>
    permission: beaconwar.admin
  reset:
    description: Full reset (clears beacons, keeps ELO)
    usage: /<command>
    permission: beaconwar.admin
  end:
    description: End game and determine winner
    usage: /<command>
    permission: beaconwar.admin
  pause:
    description: Pause all timers
    usage: /<command>
    permission: beaconwar.admin
  unpause:
    description: Resume the game
    usage: /<command>
    permission: beaconwar.admin
  join:
    description: Join a team
    usage: /<command> <red|blue>
    permission: beaconwar.use
  resistance:
    description: Set player's resistance level
    usage: /<command> <player> <0-4>
    permission: beaconwar.admin
  elo:
    description: View ELO ratings
    usage: /<command> [player|leaderboard|predict]
    permission: beaconwar.use
  quicklaunch:
    description: Auto setup, balance, countdown, start
    aliases: [ql]
    usage: /<command> [manual] [minutes]
    permission: beaconwar.admin
  status:
    description: Show game status
    usage: /<command>
    permission: beaconwar.use

permissions:
  beaconwar.use:
    description: Allows use of basic Beacon War commands
    default: true
  beaconwar.admin:
    description: Allows use of admin commands
    default: op

